apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-rag-bot
spec:
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubectl-reloader
            image: bitnami/kubectl:latest # An image with kubectl installed
            command: ["/bin/bash", "-c"]
            args:
            - |
              kubectl rollout restart deployment/rag-bot -n default
          restartPolicy: OnFailure
